import {Injectable} from '@angular/core';
import {Observable, ReplaySubject} from 'rxjs';
import {TranslateService} from '@ngx-translate/core';

function sortAlphabetically(a: any, b: any) {
  if (a.label < b.label) {
    return -1;
  } else if (a.label > b.label) {
    return 1;
  } else {
    return 0;
  }
}

@Injectable({
  providedIn: 'root'
})
export class OptionService {
  private countrySubject = new ReplaySubject(1);
  private countryObservable$ = this.countrySubject.asObservable();

  constructor(private translateService: TranslateService) {
    this.init();

    this.translateService.onLangChange.subscribe(() => {
      this.init();
    });
  }

  public getCountries(): Observable<any> {
    return this.countryObservable$;
  }

  private init(): void {
    this.initCountries();
  }

  private initCountries(): void {
    this.countrySubject.next([
        {label: this.translateService.instant('enum.countries.AD'), value: 'AD'},
        {label: this.translateService.instant('enum.countries.AE'), value: 'AE'},
        {label: this.translateService.instant('enum.countries.AF'), value: 'AF'},
        {label: this.translateService.instant('enum.countries.AG'), value: 'AG'},
        {label: this.translateService.instant('enum.countries.AI'), value: 'AI'},
        {label: this.translateService.instant('enum.countries.AL'), value: 'AL'},
        {label: this.translateService.instant('enum.countries.AM'), value: 'AM'},
        {label: this.translateService.instant('enum.countries.AO'), value: 'AO'},
        {label: this.translateService.instant('enum.countries.AQ'), value: 'AQ'},
        {label: this.translateService.instant('enum.countries.AR'), value: 'AR'},
        {label: this.translateService.instant('enum.countries.AS'), value: 'AS'},
        {label: this.translateService.instant('enum.countries.AT'), value: 'AT'},
        {label: this.translateService.instant('enum.countries.AU'), value: 'AU'},
        {label: this.translateService.instant('enum.countries.AW'), value: 'AW'},
        {label: this.translateService.instant('enum.countries.AX'), value: 'AX'},
        {label: this.translateService.instant('enum.countries.AZ'), value: 'AZ'},
        {label: this.translateService.instant('enum.countries.BA'), value: 'BA'},
        {label: this.translateService.instant('enum.countries.BB'), value: 'BB'},
        {label: this.translateService.instant('enum.countries.BD'), value: 'BD'},
        {label: this.translateService.instant('enum.countries.BE'), value: 'BE'},
        {label: this.translateService.instant('enum.countries.BF'), value: 'BF'},
        {label: this.translateService.instant('enum.countries.BG'), value: 'BG'},
        {label: this.translateService.instant('enum.countries.BH'), value: 'BH'},
        {label: this.translateService.instant('enum.countries.BI'), value: 'BI'},
        {label: this.translateService.instant('enum.countries.BJ'), value: 'BJ'},
        {label: this.translateService.instant('enum.countries.BL'), value: 'BL'},
        {label: this.translateService.instant('enum.countries.BM'), value: 'BM'},
        {label: this.translateService.instant('enum.countries.BN'), value: 'BN'},
        {label: this.translateService.instant('enum.countries.BO'), value: 'BO'},
        {label: this.translateService.instant('enum.countries.BQ'), value: 'BQ'},
        {label: this.translateService.instant('enum.countries.BR'), value: 'BR'},
        {label: this.translateService.instant('enum.countries.BS'), value: 'BS'},
        {label: this.translateService.instant('enum.countries.BT'), value: 'BT'},
        {label: this.translateService.instant('enum.countries.BV'), value: 'BV'},
        {label: this.translateService.instant('enum.countries.BW'), value: 'BW'},
        {label: this.translateService.instant('enum.countries.BY'), value: 'BY'},
        {label: this.translateService.instant('enum.countries.BZ'), value: 'BZ'},
        {label: this.translateService.instant('enum.countries.CA'), value: 'CA'},
        {label: this.translateService.instant('enum.countries.CC'), value: 'CC'},
        {label: this.translateService.instant('enum.countries.CD'), value: 'CD'},
        {label: this.translateService.instant('enum.countries.CF'), value: 'CF'},
        {label: this.translateService.instant('enum.countries.CG'), value: 'CG'},
        {label: this.translateService.instant('enum.countries.CH'), value: 'CH'},
        {label: this.translateService.instant('enum.countries.CI'), value: 'CI'},
        {label: this.translateService.instant('enum.countries.CK'), value: 'CK'},
        {label: this.translateService.instant('enum.countries.CL'), value: 'CL'},
        {label: this.translateService.instant('enum.countries.CM'), value: 'CM'},
        {label: this.translateService.instant('enum.countries.CN'), value: 'CN'},
        {label: this.translateService.instant('enum.countries.CO'), value: 'CO'},
        {label: this.translateService.instant('enum.countries.KV'), value: 'KV'},
        {label: this.translateService.instant('enum.countries.CR'), value: 'CR'},
        {label: this.translateService.instant('enum.countries.CU'), value: 'CU'},
        {label: this.translateService.instant('enum.countries.CV'), value: 'CV'},
        {label: this.translateService.instant('enum.countries.CW'), value: 'CW'},
        {label: this.translateService.instant('enum.countries.CX'), value: 'CX'},
        {label: this.translateService.instant('enum.countries.CY'), value: 'CY'},
        {label: this.translateService.instant('enum.countries.CZ'), value: 'CZ'},
        {label: this.translateService.instant('enum.countries.DE'), value: 'DE'},
        {label: this.translateService.instant('enum.countries.DJ'), value: 'DJ'},
        {label: this.translateService.instant('enum.countries.DK'), value: 'DK'},
        {label: this.translateService.instant('enum.countries.DM'), value: 'DM'},
        {label: this.translateService.instant('enum.countries.DO'), value: 'DO'},
        {label: this.translateService.instant('enum.countries.DZ'), value: 'DZ'},
        {label: this.translateService.instant('enum.countries.EC'), value: 'EC'},
        {label: this.translateService.instant('enum.countries.EE'), value: 'EE'},
        {label: this.translateService.instant('enum.countries.EG'), value: 'EG'},
        {label: this.translateService.instant('enum.countries.EH'), value: 'EH'},
        {label: this.translateService.instant('enum.countries.ER'), value: 'ER'},
        {label: this.translateService.instant('enum.countries.ES'), value: 'ES'},
        {label: this.translateService.instant('enum.countries.ET'), value: 'ET'},
        {label: this.translateService.instant('enum.countries.FI'), value: 'FI'},
        {label: this.translateService.instant('enum.countries.FJ'), value: 'FJ'},
        {label: this.translateService.instant('enum.countries.FK'), value: 'FK'},
        {label: this.translateService.instant('enum.countries.FM'), value: 'FM'},
        {label: this.translateService.instant('enum.countries.FO'), value: 'FO'},
        {label: this.translateService.instant('enum.countries.FR'), value: 'FR'},
        {label: this.translateService.instant('enum.countries.GA'), value: 'GA'},
        {label: this.translateService.instant('enum.countries.GB'), value: 'GB'},
        {label: this.translateService.instant('enum.countries.GD'), value: 'GD'},
        {label: this.translateService.instant('enum.countries.GE'), value: 'GE'},
        {label: this.translateService.instant('enum.countries.GF'), value: 'GF'},
        {label: this.translateService.instant('enum.countries.GG'), value: 'GG'},
        {label: this.translateService.instant('enum.countries.GH'), value: 'GH'},
        {label: this.translateService.instant('enum.countries.GI'), value: 'GI'},
        {label: this.translateService.instant('enum.countries.GL'), value: 'GL'},
        {label: this.translateService.instant('enum.countries.GM'), value: 'GM'},
        {label: this.translateService.instant('enum.countries.GN'), value: 'GN'},
        {label: this.translateService.instant('enum.countries.GP'), value: 'GP'},
        {label: this.translateService.instant('enum.countries.GQ'), value: 'GQ'},
        {label: this.translateService.instant('enum.countries.GR'), value: 'GR'},
        {label: this.translateService.instant('enum.countries.GS'), value: 'GS'},
        {label: this.translateService.instant('enum.countries.GT'), value: 'GT'},
        {label: this.translateService.instant('enum.countries.GU'), value: 'GU'},
        {label: this.translateService.instant('enum.countries.GW'), value: 'GW'},
        {label: this.translateService.instant('enum.countries.GY'), value: 'GY'},
        {label: this.translateService.instant('enum.countries.HK'), value: 'HK'},
        {label: this.translateService.instant('enum.countries.HM'), value: 'HM'},
        {label: this.translateService.instant('enum.countries.HN'), value: 'HN'},
        {label: this.translateService.instant('enum.countries.HR'), value: 'HR'},
        {label: this.translateService.instant('enum.countries.HT'), value: 'HT'},
        {label: this.translateService.instant('enum.countries.HU'), value: 'HU'},
        {label: this.translateService.instant('enum.countries.ID'), value: 'ID'},
        {label: this.translateService.instant('enum.countries.IE'), value: 'IE'},
        {label: this.translateService.instant('enum.countries.IL'), value: 'IL'},
        {label: this.translateService.instant('enum.countries.IM'), value: 'IM'},
        {label: this.translateService.instant('enum.countries.IN'), value: 'IN'},
        {label: this.translateService.instant('enum.countries.IO'), value: 'IO'},
        {label: this.translateService.instant('enum.countries.IQ'), value: 'IQ'},
        {label: this.translateService.instant('enum.countries.IR'), value: 'IR'},
        {label: this.translateService.instant('enum.countries.IS'), value: 'IS'},
        {label: this.translateService.instant('enum.countries.IT'), value: 'IT'},
        {label: this.translateService.instant('enum.countries.JE'), value: 'JE'},
        {label: this.translateService.instant('enum.countries.JM'), value: 'JM'},
        {label: this.translateService.instant('enum.countries.JO'), value: 'JO'},
        {label: this.translateService.instant('enum.countries.JP'), value: 'JP'},
        {label: this.translateService.instant('enum.countries.KE'), value: 'KE'},
        {label: this.translateService.instant('enum.countries.KG'), value: 'KG'},
        {label: this.translateService.instant('enum.countries.KH'), value: 'KH'},
        {label: this.translateService.instant('enum.countries.KI'), value: 'KI'},
        {label: this.translateService.instant('enum.countries.KM'), value: 'KM'},
        {label: this.translateService.instant('enum.countries.KN'), value: 'KN'},
        {label: this.translateService.instant('enum.countries.KP'), value: 'KP'},
        {label: this.translateService.instant('enum.countries.KR'), value: 'KR'},
        {label: this.translateService.instant('enum.countries.KW'), value: 'KW'},
        {label: this.translateService.instant('enum.countries.KY'), value: 'KY'},
        {label: this.translateService.instant('enum.countries.KZ'), value: 'KZ'},
        {label: this.translateService.instant('enum.countries.LA'), value: 'LA'},
        {label: this.translateService.instant('enum.countries.LB'), value: 'LB'},
        {label: this.translateService.instant('enum.countries.LC'), value: 'LC'},
        {label: this.translateService.instant('enum.countries.LI'), value: 'LI'},
        {label: this.translateService.instant('enum.countries.LK'), value: 'LK'},
        {label: this.translateService.instant('enum.countries.LR'), value: 'LR'},
        {label: this.translateService.instant('enum.countries.LS'), value: 'LS'},
        {label: this.translateService.instant('enum.countries.LT'), value: 'LT'},
        {label: this.translateService.instant('enum.countries.LU'), value: 'LU'},
        {label: this.translateService.instant('enum.countries.LV'), value: 'LV'},
        {label: this.translateService.instant('enum.countries.LY'), value: 'LY'},
        {label: this.translateService.instant('enum.countries.MA'), value: 'MA'},
        {label: this.translateService.instant('enum.countries.MC'), value: 'MC'},
        {label: this.translateService.instant('enum.countries.MD'), value: 'MD'},
        {label: this.translateService.instant('enum.countries.ME'), value: 'ME'},
        {label: this.translateService.instant('enum.countries.MF'), value: 'MF'},
        {label: this.translateService.instant('enum.countries.MG'), value: 'MG'},
        {label: this.translateService.instant('enum.countries.MH'), value: 'MH'},
        {label: this.translateService.instant('enum.countries.MK'), value: 'MK'},
        {label: this.translateService.instant('enum.countries.ML'), value: 'ML'},
        {label: this.translateService.instant('enum.countries.MM'), value: 'MM'},
        {label: this.translateService.instant('enum.countries.MN'), value: 'MN'},
        {label: this.translateService.instant('enum.countries.MO'), value: 'MO'},
        {label: this.translateService.instant('enum.countries.MP'), value: 'MP'},
        {label: this.translateService.instant('enum.countries.MQ'), value: 'MQ'},
        {label: this.translateService.instant('enum.countries.MR'), value: 'MR'},
        {label: this.translateService.instant('enum.countries.MS'), value: 'MS'},
        {label: this.translateService.instant('enum.countries.MT'), value: 'MT'},
        {label: this.translateService.instant('enum.countries.MU'), value: 'MU'},
        {label: this.translateService.instant('enum.countries.MV'), value: 'MV'},
        {label: this.translateService.instant('enum.countries.MW'), value: 'MW'},
        {label: this.translateService.instant('enum.countries.MX'), value: 'MX'},
        {label: this.translateService.instant('enum.countries.MY'), value: 'MY'},
        {label: this.translateService.instant('enum.countries.MZ'), value: 'MZ'},
        {label: this.translateService.instant('enum.countries.NA'), value: 'NA'},
        {label: this.translateService.instant('enum.countries.NC'), value: 'NC'},
        {label: this.translateService.instant('enum.countries.NE'), value: 'NE'},
        {label: this.translateService.instant('enum.countries.NF'), value: 'NF'},
        {label: this.translateService.instant('enum.countries.NG'), value: 'NG'},
        {label: this.translateService.instant('enum.countries.NI'), value: 'NI'},
        {label: this.translateService.instant('enum.countries.NL'), value: 'NL'},
        {label: this.translateService.instant('enum.countries.NO'), value: 'NO'},
        {label: this.translateService.instant('enum.countries.NP'), value: 'NP'},
        {label: this.translateService.instant('enum.countries.NR'), value: 'NR'},
        {label: this.translateService.instant('enum.countries.NU'), value: 'NU'},
        {label: this.translateService.instant('enum.countries.NZ'), value: 'NZ'},
        {label: this.translateService.instant('enum.countries.OM'), value: 'OM'},
        {label: this.translateService.instant('enum.countries.PA'), value: 'PA'},
        {label: this.translateService.instant('enum.countries.PE'), value: 'PE'},
        {label: this.translateService.instant('enum.countries.PF'), value: 'PF'},
        {label: this.translateService.instant('enum.countries.PG'), value: 'PG'},
        {label: this.translateService.instant('enum.countries.PH'), value: 'PH'},
        {label: this.translateService.instant('enum.countries.PK'), value: 'PK'},
        {label: this.translateService.instant('enum.countries.PL'), value: 'PL'},
        {label: this.translateService.instant('enum.countries.PM'), value: 'PM'},
        {label: this.translateService.instant('enum.countries.PN'), value: 'PN'},
        {label: this.translateService.instant('enum.countries.PR'), value: 'PR'},
        {label: this.translateService.instant('enum.countries.PS'), value: 'PS'},
        {label: this.translateService.instant('enum.countries.PT'), value: 'PT'},
        {label: this.translateService.instant('enum.countries.PW'), value: 'PW'},
        {label: this.translateService.instant('enum.countries.PY'), value: 'PY'},
        {label: this.translateService.instant('enum.countries.QA'), value: 'QA'},
        {label: this.translateService.instant('enum.countries.RE'), value: 'RE'},
        {label: this.translateService.instant('enum.countries.RO'), value: 'RO'},
        {label: this.translateService.instant('enum.countries.RS'), value: 'RS'},
        {label: this.translateService.instant('enum.countries.RU'), value: 'RU'},
        {label: this.translateService.instant('enum.countries.RW'), value: 'RW'},
        {label: this.translateService.instant('enum.countries.SA'), value: 'SA'},
        {label: this.translateService.instant('enum.countries.SB'), value: 'SB'},
        {label: this.translateService.instant('enum.countries.SC'), value: 'SC'},
        {label: this.translateService.instant('enum.countries.SD'), value: 'SD'},
        {label: this.translateService.instant('enum.countries.SE'), value: 'SE'},
        {label: this.translateService.instant('enum.countries.SG'), value: 'SG'},
        {label: this.translateService.instant('enum.countries.SH'), value: 'SH'},
        {label: this.translateService.instant('enum.countries.SI'), value: 'SI'},
        {label: this.translateService.instant('enum.countries.SJ'), value: 'SJ'},
        {label: this.translateService.instant('enum.countries.SK'), value: 'SK'},
        {label: this.translateService.instant('enum.countries.SL'), value: 'SL'},
        {label: this.translateService.instant('enum.countries.SM'), value: 'SM'},
        {label: this.translateService.instant('enum.countries.SN'), value: 'SN'},
        {label: this.translateService.instant('enum.countries.SO'), value: 'SO'},
        {label: this.translateService.instant('enum.countries.SR'), value: 'SR'},
        {label: this.translateService.instant('enum.countries.SS'), value: 'SS'},
        {label: this.translateService.instant('enum.countries.ST'), value: 'ST'},
        {label: this.translateService.instant('enum.countries.SV'), value: 'SV'},
        {label: this.translateService.instant('enum.countries.SX'), value: 'SX'},
        {label: this.translateService.instant('enum.countries.SY'), value: 'SY'},
        {label: this.translateService.instant('enum.countries.SZ'), value: 'SZ'},
        {label: this.translateService.instant('enum.countries.TC'), value: 'TC'},
        {label: this.translateService.instant('enum.countries.TD'), value: 'TD'},
        {label: this.translateService.instant('enum.countries.TF'), value: 'TF'},
        {label: this.translateService.instant('enum.countries.TG'), value: 'TG'},
        {label: this.translateService.instant('enum.countries.TH'), value: 'TH'},
        {label: this.translateService.instant('enum.countries.TJ'), value: 'TJ'},
        {label: this.translateService.instant('enum.countries.TK'), value: 'TK'},
        {label: this.translateService.instant('enum.countries.TL'), value: 'TL'},
        {label: this.translateService.instant('enum.countries.TM'), value: 'TM'},
        {label: this.translateService.instant('enum.countries.TN'), value: 'TN'},
        {label: this.translateService.instant('enum.countries.TO'), value: 'TO'},
        {label: this.translateService.instant('enum.countries.TR'), value: 'TR'},
        {label: this.translateService.instant('enum.countries.TT'), value: 'TT'},
        {label: this.translateService.instant('enum.countries.TV'), value: 'TV'},
        {label: this.translateService.instant('enum.countries.TW'), value: 'TW'},
        {label: this.translateService.instant('enum.countries.TZ'), value: 'TZ'},
        {label: this.translateService.instant('enum.countries.UA'), value: 'UA'},
        {label: this.translateService.instant('enum.countries.UG'), value: 'UG'},
        {label: this.translateService.instant('enum.countries.UM'), value: 'UM'},
        {label: this.translateService.instant('enum.countries.US'), value: 'US'},
        {label: this.translateService.instant('enum.countries.UY'), value: 'UY'},
        {label: this.translateService.instant('enum.countries.UZ'), value: 'UZ'},
        {label: this.translateService.instant('enum.countries.VA'), value: 'VA'},
        {label: this.translateService.instant('enum.countries.VC'), value: 'VC'},
        {label: this.translateService.instant('enum.countries.VE'), value: 'VE'},
        {label: this.translateService.instant('enum.countries.VG'), value: 'VG'},
        {label: this.translateService.instant('enum.countries.VI'), value: 'VI'},
        {label: this.translateService.instant('enum.countries.VN'), value: 'VN'},
        {label: this.translateService.instant('enum.countries.VU'), value: 'VU'},
        {label: this.translateService.instant('enum.countries.WF'), value: 'WF'},
        {label: this.translateService.instant('enum.countries.WS'), value: 'WS'},
        {label: this.translateService.instant('enum.countries.XX'), value: 'XX'},
        {label: this.translateService.instant('enum.countries.YE'), value: 'YE'},
        {label: this.translateService.instant('enum.countries.YT'), value: 'YT'},
        {label: this.translateService.instant('enum.countries.ZA'), value: 'ZA'},
        {label: this.translateService.instant('enum.countries.ZM'), value: 'ZM'},
        {label: this.translateService.instant('enum.countries.ZW'), value: 'ZW'}
      ].sort(sortAlphabetically)
    );
  }
}
