import { writeFileSync } from 'fs';
import { dedent } from 'tslint/lib/utils';

const util = require('util');
const exec = util.promisify(require('child_process').exec);

async function createVersionsFile(filename: string) {
  const revision = (await exec('git rev-parse --short HEAD')).stdout.toString().trim();
  const branch = (await exec('git rev-parse --abbrev-ref HEAD')).stdout.toString().trim();

  const content = dedent`// this file is automatically generated by build.information.ts script
export const build = {
  version: '${process.env.npm_package_version}',
  revision: '${revision}',
  branch: '${branch}'
};
`;

  writeFileSync(filename, content, {encoding: 'utf8'});
}

createVersionsFile('src/environments/build-information.ts');
